package main

const HTTP_CODE_INVALID_JSON = "INVALID_JSON"
const HTTP_CODE_VALIDATION_ERROR = "VALIDATION_ERROR"
const HTTP_CODE_INTERNAL = "INTERNAL"
const HTTP_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
const HTTP_UNAUTHORIZED = "UNAUTHORIZED"

const MSG_INVALID_BODY_REQUEST = "Invalid body request"
const MSG_SOMETHING_WENT_WRONG = "Something went wrong"
